version: "3.7"

services:

  curriculum:
    build:
      context: .
      dockerfile: dockerfile
      args:
        EXPOSE: ${APP_PORT}
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 150M
    ports:
      - ${APP_PORT}:${APP_PORT}
    
