version: "3.7"

services:
  curriculum:
    container_name: curriculum
    image: monolith/hexagonal/curriculum
    networks:
      - curriculum

networks:
  curriculum:
    name: curriculum
    driver: bridge
