# Production image, copy all the files and run next
FROM node:18-alpine3.15 AS runner
ARG EXPOSE
# Set working directory
WORKDIR /usr/src/app
COPY package.json ./
# RUN npm install --omit=dev
RUN yarn install --omit=dev
# COPY --from=builder /app/dist ./dist

EXPOSE $EXPOSE
# Runner
CMD [ "node","dist/main.js" ]